version: "3.7"

services:
  backend:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: trademaker
      POSTGRES_PASSWORD: trademaker
      POSTGRES_DB: trademaker
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: trademaker
      POSTGRES_PASSWORD: trademaker
      POSTGRES_DB: trademaker
